### ISSUE TITLE
sass support?

### ISSUE THREAD

**Issue by antonkluev** [gioacostax/atom-vive-syntax#1]
:)

**Comment by gioacostax** [comment]
Same as SCSS.

Yes. :)

**Comment by antonkluev** [comment]
hm... :)

![untitled 2](https://cloud.githubusercontent.com/assets/12466732/23710349/b22cc0e8-041c-11e7-8e6e-c7461b759913.jpeg)

**Comment by gioacostax** [comment]
Mmm, forgot the last Atom update.

Fixed: [edcbeb5](https://github.com/gioacostax/atom-vive-syntax/commit/edcbeb5a377bfd8a019eccace4f54a72f3cc2d0f)
